name: Deploy Next.js Application

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-nextjs
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN }}

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

    - name: Deploy application via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} '
          # Verify Node.js version
          # node --version 2>&1
          
          echo "Setting up environment for Node.js..." &&
          export NVM_DIR="$HOME/.nvm" &&
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" &&
          nvm use node &&

          # cd updone/updone-talentpro &&
          cd ../var/www/updone-talentpro &&
          echo "Pulling latest code..." 2>&1 &&
          git stash
          git pull 2>&1 &&

          # echo "Removing old node_modules and .next directory..." 2>&1 &&
          # rm -rf .next 2>&1 &&

          # echo "Stopping all applications with PM2..." 2>&1 &&
          # pm2 stop 0 2>&1
          # pm2 stop 1 2>&1
          # pm2 stop 2 2>&1

          echo "Installing dependencies..." 2>&1 &&
          # NODE_OPTIONS="--max-old-space-size=4096" npm install --verbose 2>&1 &&
          npm install --verbose 2>&1 &&

          echo "Building application..." 2>&1 &&
          npm run build 2>&1 &&
          
          echo "Restarting application with PM2..." 2>&1 &&
          pm2 restart 4 2>&1
          # pm2 restart 1 2>&1
          # pm2 restart 2 2>&1
        '
